markdown: kramdown
safe: false
permalink: /:categories/:title
exclude:
  - README.md
origin: https://tobi.pub
name: iF时代设计平台
title: 做最专业的装修设计平台

defaults:
  - scope:
        path: blog/_posts
        type: posts
    values:
        permalink: blog/posts/:title
        layout: post
  - scope:
        path: discovery/_posts
    values:
        layout: post

blog:
    name: 陈凸立
    desc: 陈凸立的代码笔记

    category:
        thinking: 闭门思考
        experience: 问题即经验
        criticism: 非专业吐槽
        communication: 交流分享
    categories:
      - name:  thinking
        title: 闭门思考

      - name:  experience
        title: 问题即经验

      - name:  criticism
        title: 非专业吐槽

      - name: communication
        title: 交流分享

    scrollingLoadCount: 0

meta:
    author:
        name: Tobi
        email: iftimes@qq.com
